include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: true
    strict-raw-types: true
  errors:
    implicit_dynamic_parameter: warning
    invalid_annotation_target: ignore
