include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - use_super_parameters

analyzer:
  plugins:
    - custom_lint
  language:
    strict-casts: true
    strict-raw-types: true
    strict-inference: true
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore
    collection_methods_unrelated_type: error
