name: sideswap_websocket
description: Sideswap local endpoint websocket
version: 0.0.3
publish_to: none

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  basic_utils: ^5.7.0
  flutter:
    sdk: flutter
  fpdart: ^1.1.0
  freezed_annotation: ^2.4.1
  hooks_riverpod: ^2.4.6
  json_annotation: ^4.8.1
  pointycastle: ^3.7.3
  shelf: ^1.4.1
  shelf_web_socket: ^1.0.4
  sideswap_logger:
    git:
      url: https://github.com/sideswap-io/sideswap_logger.git
      ref: master
  uuid: ^4.2.1
  web_socket_channel: ^2.4.0
  websocket_universal: ^1.1.1

dev_dependencies:
  base_codecs: ^1.0.1
  build_runner: ^2.4.6
  custom_lint: ^0.5.6
  flutter_hooks: ^0.20.3
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  mockito: ^5.4.2
  riverpod_lint: ^2.3.4
  test: ^1.24.9

# Remove when mockito will support same analyzer as riverpod_lint
dependency_overrides:
  analyzer: ^6.0.0

flutter:
