name: sideswap_websocket
description: Sideswap local endpoint websocket
version: 0.0.8
publish_to: none

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  basic_utils: ^5.7.0
  flutter:
    sdk: flutter
  fpdart: ^1.1.0
  freezed_annotation: ^2.4.1
  hooks_riverpod: ^2.5.1
  json_annotation: ^4.9.0
  pointycastle: ^3.9.1
  shelf: ^1.4.1
  shelf_web_socket: ^1.0.4
  sideswap_logger:
    git:
      url: https://github.com/sideswap-io/sideswap_logger.git
      ref: master
  uuid: ^4.4.0
  web_socket_channel: ^2.4.5
  websocket_universal: ^1.2.5

dev_dependencies:
  base_codecs: ^1.0.1
  build_runner: ^2.4.9
  custom_lint: ^0.6.4
  flutter_hooks: ^0.20.5
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  riverpod_lint: ^2.3.10
  test: ^1.25.2

flutter:
